package scenario

import (
	"github.com/solguardlabs/northstardtl/src/api"
	"github.com/solguardlabs/northstardtl/src/domain"
	"github.com/solguardlabs/northstardtl/src/routing"
)

func DefaultBootstrap() api.Bootstrap {
	return api.Bootstrap{
		Epoch:  1,
		Policy: routing.DefaultPolicy(),
		Routes: []domain.Route{
			{
				ID:               "route:north-prime",
				DisplayName:      "North Prime RFQ",
				SourceAsset:      "usdc",
				DestinationAsset: "eurc",
				SourceTreasury:   "acct:north-prime-usdc",
				DestinationVault: "acct:north-prime-eurc",
				FeeAccount:       "acct:fees",
				RatePpm:          1_010_000,
				BaseFeeBps:       10,
				FlatFee:          50,
				CongestionBps:    0,
				CongestionLevel:  0,
				LatencyMillis:    85,
				HealthBps:        9_900,
				Preferred:        true,
				PreferredBias:    20_000,
				MinAmount:        10_000,
				MaxAmount:        250_000,
				MaxExposure:      900_000,
				OutputLiquidity:  2_000_000,
				Status:           domain.RouteActive,
				SettlementDelay:  1,
			},
			{
				ID:               "route:polar-deep",
				DisplayName:      "Polar Deep Pool",
				SourceAsset:      "usdc",
				DestinationAsset: "eurc",
				SourceTreasury:   "acct:polar-deep-usdc",
				DestinationVault: "acct:polar-deep-eurc",
				FeeAccount:       "acct:fees",
				RatePpm:          970_000,
				BaseFeeBps:       8,
				FlatFee:          40,
				CongestionBps:    120,
				CongestionLevel:  25,
				LatencyMillis:    130,
				HealthBps:        9_700,
				Preferred:        false,
				MinAmount:        10_000,
				MaxAmount:        400_000,
				MaxExposure:      1_500_000,
				OutputLiquidity:  2_500_000,
				Status:           domain.RouteActive,
				SettlementDelay:  1,
			},
			{
				ID:               "route:boreal-bulk",
				DisplayName:      "Boreal Bulk Netting",
				SourceAsset:      "usdc",
				DestinationAsset: "eurc",
				SourceTreasury:   "acct:boreal-bulk-usdc",
				DestinationVault: "acct:boreal-bulk-eurc",
				FeeAccount:       "acct:fees",
				RatePpm:          1_000_000,
				BaseFeeBps:       14,
				FlatFee:          20,
				CongestionBps:    850,
				CongestionLevel:  200,
				LatencyMillis:    240,
				HealthBps:        9_250,
				Preferred:        false,
				MinAmount:        50_000,
				MaxAmount:        600_000,
				MaxExposure:      2_000_000,
				OutputLiquidity:  3_000_000,
				Status:           domain.RouteActive,
				SettlementDelay:  2,
			},
			{
				ID:               "route:aurora-rfq",
				DisplayName:      "Aurora RFQ Lane",
				SourceAsset:      "usdc",
				DestinationAsset: "eurc",
				SourceTreasury:   "acct:aurora-rfq-usdc",
				DestinationVault: "acct:aurora-rfq-eurc",
				FeeAccount:       "acct:fees",
				RatePpm:          985_000,
				BaseFeeBps:       6,
				FlatFee:          75,
				CongestionBps:    60,
				CongestionLevel:  10,
				LatencyMillis:    95,
				HealthBps:        9_550,
				Preferred:        false,
				MinAmount:        5_000,
				MaxAmount:        125_000,
				MaxExposure:      650_000,
				OutputLiquidity:  1_200_000,
				Status:           domain.RouteActive,
				SettlementDelay:  1,
			},
		},
		Balances: []domain.BalanceSeed{
			{Account: "acct:alice", Asset: "usdc", Available: 1_500_000},
			{Account: "acct:carol", Asset: "usdc", Available: 900_000},
			{Account: "acct:bob", Asset: "eurc", Available: 0},
			{Account: "acct:fees", Asset: "usdc", Available: 0},
		},
	}
}

func DefaultIntent(id domain.IntentID, amount domain.Money) domain.Intent {
	return domain.Intent{
		ID:                   id,
		SourceAccount:        "acct:alice",
		DestinationAccount:   "acct:bob",
		SourceAsset:          "usdc",
		DestinationAsset:     "eurc",
		Amount:               amount,
		MinDestinationAmount: 1,
		MaxFee:               1_000,
		Priority:             domain.PriorityPreferred,
	}
}
